// Learn more about DAX queries at https://aka.ms/dax-queries

// Here is a sample DAX query from your model, click 'Run'
// Try other DAX queries by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
EVALUATE
    
SUMMARIZE (
    Sales,
    Sales[Channel],
    'Date'[Month - Year],
    "Category", "Revenue",
    "First Date", MIN ( 'Date'[Date] ),
    "Sales Values", [Total Sales]
)


EVALUATE
SUMMARIZE(
    FILTER(
        'Channel Revenues',
        'Channel Revenues'[Category] = "Distributor"
    ),
    'Channel Revenues'[Channel],
    "Total Revenue", SUM('Channel Revenues'[Sales Values])
)


EVALUATE
SUMMARIZE(
    'Channel Revenues',
    'Channel Revenues'[Channel],
    "Total Revenue", SUM('Channel Revenues'[Sales Values])
)




EVALUATE
FILTER(
    SUMMARIZE(
        'Channel Revenues',
        'Channel Revenues'[Channel],
        "Total Revenue", SUM('Channel Revenues'[Sales Values])
    ),
    'Channel Revenues'[Channel] = "Distributor"
)




