table Regions
	lineageTag: 7eb77021-0624-445b-b638-7c4443a6be0b

	column Index
		dataType: int64
		formatString: 0
		lineageTag: bcc0bc3a-b1ff-4104-97ee-a7fa097f7046
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: aeb54457-2235-48a3-a148-12362802fd93
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e36f7550-18bf-466d-93f0-f68317af4fa1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: f04410a4-46be-41ce-a153-b6a98b981973
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: 1f7bc3d5-2692-4bed-820d-5c6ddca4b3a7
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	partition Regions = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\julia\Downloads\Financial Reporting In Power BI.xlsx"), null, true),
				    Regions_Sheet = Source{[Item="Regions",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Regions_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Index", Int64.Type}, {"City", type text}, {"Country", type text}, {"Territory", type text}, {"Full Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

