table 'Balance Sheet Data'
	lineageTag: 5a15d90a-3d85-4205-bd07-1f791102901a

	column 'Balance Sheet Type'
		dataType: string
		lineageTag: fb8d8631-6e74-4c9f-aec0-2974a6c40842
		summarizeBy: none
		sourceColumn: Balance Sheet Type

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f2009b68-f85e-400a-92bd-fd138359b083
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: 640b3b19-3f87-4016-8f01-fbbe01719f01
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: d354e2a4-1e77-4754-8721-dc26c2fcf0fe
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 03668eff-abfc-4777-b387-2e29497bcb89
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Balance Sheet Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\julia\Downloads\Financial Reporting In Power BI.xlsx"), null, true),
				    #"Balance Sheet Data_Sheet" = Source{[Item="Balance Sheet Data",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Balance Sheet Data_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", Int64.Type}, {"Column5", type number}, {"Column6", type number}, {"Column7", type number}, {"Column8", type number}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Balance Sheet Type", type text}, {"Category", type text}, {"Sub Category", type text}, {"2014", Int64.Type}, {"2015", type number}, {"2016", type number}, {"2017", type number}, {"2018", type number}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Balance Sheet Type", "Category", "Sub Category"}, "Attribute", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

