table 'CF Template'
	lineageTag: 8e9f79eb-ad2c-43b2-a0d2-71a16d477d28

	column 'Row Index'
		dataType: int64
		formatString: 0
		lineageTag: 9a9adce6-8132-4d69-b811-fbe879ae4b3b
		summarizeBy: sum
		sourceColumn: Row Index

		annotation SummarizationSetBy = Automatic

	column 'Cash Flow Items'
		dataType: string
		lineageTag: a0e738b6-a140-4419-870d-ea680064460a
		summarizeBy: none
		sourceColumn: Cash Flow Items

		annotation SummarizationSetBy = Automatic

	column 'Cash Flow Summary Items'
		dataType: string
		lineageTag: 191d0a42-d11a-40b9-a882-875adaa150e7
		summarizeBy: none
		sourceColumn: Cash Flow Summary Items

		annotation SummarizationSetBy = Automatic

	column 'Cash Flow Normalized'
		dataType: string
		lineageTag: a87dabb7-c543-4f5d-9eee-f00208ac7a3b
		summarizeBy: none
		sourceColumn: Cash Flow Normalized

		annotation SummarizationSetBy = Automatic

	column 'Summary Index'
		dataType: int64
		formatString: 0
		lineageTag: 84b0cae6-39c3-4ceb-bf25-ce66df41c932
		summarizeBy: sum
		sourceColumn: Summary Index

		annotation SummarizationSetBy = Automatic

	partition 'CF Template' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\julia\Downloads\Financial Reporting In Power BI.xlsx"), null, true),
				    #"CF Template_Sheet" = Source{[Item="CF Template",Kind="Sheet"]}[Data],
				    #"Promoted Headers1" = Table.PromoteHeaders(#"CF Template_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Row Index", Int64.Type}, {"Cash Flow Items", type text}, {"Cash Flow Summary Items", type text}, {"Cash Flow Normalized", type text}, {"Summary Index", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

