table Products
	lineageTag: a3d0dc07-388e-4e3a-b876-7fd677b071c2

	column Index
		dataType: int64
		formatString: 0
		lineageTag: fd1e1de0-bbf3-4d14-b10e-1cd68f79451f
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 189139af-168d-449a-833b-376884bc8b47
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\julia\Downloads\Financial Reporting In Power BI.xlsx"), null, true),
				    Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Index", Int64.Type}, {"Product Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

